export const patientForm = {
  name: {
    title: "İsim",
    placeholder: "Lütfen İsim Giriniz",
    type: "text",
    for: "name",
    required: true,
  },
  surname: {
    title: "Soyisim",
    placeholder: "Lütfen Soyisim Giriniz",
    type: "text",
    for: "surname",
    required: true,
  },
  birthDate: {
    title: "Doğum Tarihi",
    type: "date",
    for: "birthDate",
    // placeholder: "Gün / Ay / Yıl",
    required: true,
    // mask: true,
    // masked: [/[1-9]/, /\d/, "/", /\d/, /\d/, "/", /\d/, /\d/, /\d/, /\d/]
  },
  birthPlace: {
    title: "Doğum Yeri",
    placeholder: "Lütfen Doğum Yeri Giriniz",
    for: "birthPlace",
  },
  fatherName: {
    title: "Baba Adı",
    placeholder: "Lütfen İsim Giriniz",
    type: "text",
    for: "fatherName",
  },
  motherName: {
    title: "Anne Adı",
    placeholder: "Lütfen İsim Giriniz",
    type: "text",
    for: "motherName",
  },
  gender: {
    title: "Cinsiyet",
    type: "radio",
    for: "gender",
    required: true,
  },
  bloodtype: {
    title: "Kan Grubu",
    placeholder: "Kan Grubu Giriniz",
    for: "bloodtype",
  },
  tc: {
    title: "T.C. Numarası",
    placeholder: "Lütfen T.C. Numarası Giriniz",
    type: "text",
    for: "tc",
    required: true,
    mask: true,
    masked: [
      /[1-9]/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      /\d/,
    ],
  },
  passportNo: {
    title: "Pasaport Numarası",
    placeholder: "Lütfen Pasaport Numarası Giriniz",
    type: "number",
    for: "passportNo",
  },
  mobilePhone: {
    title: "Cep Telefonu",
    placeholder: "Lütfen Telefon Numarası Giriniz",
    type: "tel",
    for: "mobilePhone",
    mask: true,
    masked: [
      "(",
      /[1-9]/,
      /\d/,
      /\d/,
      ")",
      " ",
      /\d/,
      /\d/,
      /\d/,
      "-",
      /\d/,
      /\d/,
      /\d/,
      /\d/,
    ],
  },
  workPhone: {
    title: "İş Telefonu",
    placeholder: "Lütfen Telefon Numarası Giriniz",
    type: "tel",
    for: "workPhone",
  },
  emergencyMobilePhone: {
    title: "Acil Durum Telefonu",
    placeholder: "Lütfen Telefon Numarası Giriniz",
    type: "tel",
    for: "emergencyMobilePhone",
    mask: true,
    masked: [
      "(",
      /[1-9]/,
      /\d/,
      /\d/,
      ")",
      " ",
      /\d/,
      /\d/,
      /\d/,
      "-",
      /\d/,
      /\d/,
      /\d/,
      /\d/,
    ],
  },
  email: {
    title: "Email Adresi",
    placeholder: "Email adresi giriniz",
    type: "text",
    for: "email",
    required: false,
  },
  profession: {
    title: "Meslek",
    placeholder: "Lütfen Meslek Giriniz",
    type: "text",
    for: "profession",
  },
  homeAddress: {
    title: "Ev Adresi",
    placeholder: "Lütfen Ev Adresi Giriniz",
    type: "text",
    for: "homeAddress",
  },
  canSendSms: {
    title: "Bildirim Onayı",
    placeholder: "SMS ve E-Posta Gönderimini Onaylıyorum",
    type: "checkbox",
    for: "canSendSms",
  },
  color: {
    title: "Renk Seçimi",
    type: "radio",
    for: "color",
  },
  diseases: {
    title: "Hastalıklar",
    type: "radio",
    for: "diseases",
  },
  documentNo: {
    title: "Dosya Numarası",
    type: "text",
    for: "documentNo",
    placeholder: "Lütfen Dosya Numarası Giriniz",
    required: true,
  },
  note: {
    title: "Not",
    type: "text",
    for: "note",
    placeholder: "Not Giriniz",
  },
  tag: {
    title: "Rahatsızlıklar",
    type: "text",
    for: "tag",
    placeholder: "Rahatsızlık Giriniz",
  },
};

export const signForm = {
  email: {
    title: "Kullanıcı Adı",
    placeholder: "Lütfen kullanıcı adı giriniz",
    type: "text",
    for: "email",
    required: true,
  },
  password: {
    title: "Şifre",
    placeholder: "Lütfen şifre giriniz",
    type: "password",
    for: "password",
    required: true,
  },
  confirmPassword: {
    title: "Şifre",
    placeholder: "Lütfen şifre giriniz",
    type: "password",
    for: "confirmPassword",
  },
};
